#
#######################################################################################
#
FROM redis:alpine
#
LABEL maintainer="Franz Branntvino"
LABEL Name=redis-server
LABEL Version=0.0.1
#
#######################################################################################
#
EXPOSE 6379
#
# simple run:
# docker run --name some-redis -d redis redis-server --appendonly yes
# More on: https://hub.docker.com/_/redis/
#
